import Nav from "@/components/Nav";
import "./globals.css";
import AuthStatus from "@/components/authStatus";

import SessionProviderWrapper from "@/utils/sessionProviderWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionProviderWrapper>
      <html lang="en">
        <body>
          <div className="flex flex-row">
            <div className="w-4/5 p-3 h-screen bg-black">{children}</div>
            <div className="w-1/5 p-3 h-screen bg-gray-700">
              <h2 className="text-3xl mb-4 text-white">Menus</h2>
              <AuthStatus />

              <hr />

              <Nav />
            </div>
          </div>
        </body>
      </html>
    </SessionProviderWrapper>
  );
}
